// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using student_management.DataContext;

namespace student_management.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAcessLayer.student", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cnic_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("entry_date_time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("father_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("full_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("roll_no")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Students");
                });
            //modelBuilder.Entity("DataAcessLayer.Teacher", b =>
            //{
            //    b.Property<int>("id")
            //           .ValueGeneratedOnAdd()
            //           .HasColumnType("int")
            //           .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
            //    b.Property<string>("teacher_name")
            //           .HasColumnType("nvarchar(max)");
            //    b.Property<string>("cnic_no")
            //          .HasColumnType("nvarchar(max)");
            //    b.Property<string>("address")
            //          .HasColumnType("nvarchar(max)");
            //    b.Property<string>("description")
            //          .HasColumnType("nvarchar(max)");
            //    b.Property<string>("contact_no")
            //          .HasColumnType("nvarchar(max)");
            //});

#pragma warning restore 612, 618
        }
    }
}
